### ISSUE TITLE
Create shorter version of calling Ystock

### ISSUE THREAD

**Issue by wakproductions** [gregwinn/ystock#7]
Since the Google API is defunct, it might be better to make a module that delegates calls to the Yahoo module so that rather then doing

    Ystock::Yahoo.get_quote('BABA')

you can just call it like

    Ystock.get_quote('BABA')

Want me to make a pull request?

**Comment by gregwinn** [comment]
Hello,
     I agree, If you would like to do that yes please create a pull request and once reviewed I will release it!

If not I will consider this ticket an improvement and start on the work myself. Just let me know!

Thanks!

**Comment by gregwinn** [comment]
I had a little extra time so I completed your request for a shorter call.

You can now use:
```
Ystock.quote("aapl")
```

https://github.com/gregwinn/ystock/commit/b9c7482d0b21c14585ede45838765a6ddd2f4a34

**Comment by wakproductions** [comment]
Awesome! Thanks for the update.
